Repository Pageworks/djinnjs, pull requests merged in 2020-01, with the labels that each got.

#11 Pjax Updates
  changelog.md
  cli/cli.js
  cli/lib/config-checker.js
  package-lock.json
  src/core/config.ts
  src/core/pjax-worker.ts
  src/core/pjax.ts
  src/core/runtime.ts
Labels: bug, enhancement

#12 DjinnJS v0.0.9
  .gitignore
  changelog.md
  cleanup.js
  cli/cli.js
  cli/lib/config-checker.js
  package-lock.json
  package.json
  relocate.js
  src/core/config.ts
  src/core/env.ts
  src/core/fetch-css.ts
  src/core/fetch-js.ts
  src/core/fetch.ts
  src/core/runtime.ts
Labels: enhancement

#18 Fixed service worker redirects
  changelog.md
  src/core/service-worker.js
Labels: bug

#21 Fixed Pjaxing inline scripts
  changelog.md
  package-lock.json
  src/core/pjax.ts
  src/core/runtime.ts
Labels: bug

#24 Fixed src array bug
  changelog.md
  cli/lib/config-checker.js
  cli/lib/css.js
  cli/lib/scrubber.js
Labels: bug

#22 Feature/#20 custom element prefix
  changelog.md
  package.json
  src/core/fetch.ts
  src/core/runtime.ts
  src/core/service-worker.js
Labels: enhancement

#25 Notifications Update
  .prettierrc
  changelog.md
  cli/cli.js
  cli/lib/css.js
  package-lock.json
  package.json
  relocate.js
  src/core/actor.ts
  src/core/broadcast-worker.ts
  src/core/broadcaster.ts
  src/core/config.ts
  src/core/env.ts
  src/core/fetch-css.ts
  src/core/fetch-js.ts
  src/core/fetch.ts
  src/core/messages.d.ts
  src/core/pjax-worker.ts
  src/core/pjax.ts
  src/core/runtime-worker.ts
  src/core/runtime.ts
  src/core/transition-manager.ts
  src/packages/notify.js
  src/transitions/fade.ts
  src/transitions/none.ts
  src/transitions/slide.ts
  src/web_modules/@codewithkyle/notifications.js
  src/web_modules/@codewithkyle/pjax-notification.css
  tsconfig.json
Labels: enhancement

#27 Fixed disableServiceWorker bug
  changelog.md
  cli/cli.js
  package-lock.json
  src/core/config.ts
  src/core/pjax.ts
Labels: Hotfix

#31 Hotfix - Pjax view verification
  changelog.md
  src/core/pjax.ts
Labels: Hotfix

#32 Fixes broken Pjax ID attributes
  changelog.md
  package-lock.json
  src/core/pjax.ts
Labels: Hotfix

#33 Windows path name fix
  changelog.md
  cli/cli.js
  relocate.js
Labels: Hotfix

#37 Fixed fetchJS external URL bug
  changelog.md
  src/core/fetch.ts
Labels: Hotfix

#41 Closes #40 - fixed script scrubber regex issue
  changelog.md
  cli/lib/scrubber.js
Labels: Hotfix

#38 Closes #36 - fixes page scroll position & hash in url on page load
  changelog.md
  src/core/runtime.ts
Labels: Hotfix

#44 Hotfix - #39 pjax page jumps
  changelog.md
  src/core/pjax.ts
Labels: Hotfix

#23 Default Transitions Update
  changelog.md
  package-lock.json
  package.json
  src/core/pjax.ts
  src/core/transition-manager.ts
  src/transitions/fade.ts
  src/transitions/none.ts
  src/transitions/slide.ts
Labels: enhancement

#46 Fixed Terser minify methods error reporting bug
  changelog.md
  cli/lib/minifier.js
  package-lock.json
Labels: Hotfix
